name: Backup MongoDB Atlas Diário

on:
  schedule:
    # Executa todo dia às 2h da manhã (UTC)
    - cron: '0 2 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      BACKUP_DIR: './backup'

    steps:
      - name: Checar o ambiente
        run: |
          mongodump --version
          mkdir -p $BACKUP_DIR

      - name: Fazer backup do MongoDB Atlas
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          BACKUP_PATH="$BACKUP_DIR/dump-$TIMESTAMP"
          mongodump --uri="$MONGO_URI" --out="$BACKUP_PATH"
          echo "Backup criado em $BACKUP_PATH"

      - name: Remover backups com mais de 90 dias
        run: |
          find $BACKUP_DIR -type d -name "dump-*" -mtime +90 -exec rm -rf {} +
          echo "Backups antigos removidos"

      # Opcional: listar backups restantes
      - name: Listar backups restantes
        run: ls -l $BACKUP_DIR
