name: Restaurar Backup MongoDB

on:
  workflow_dispatch:
    inputs:
      artifact-name:
        description: 'Nome do artifact de backup para restaurar'
        required: false
        default: mongo-backup

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar backup artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.inputs['artifact-name'] }}

    - name: Instalar mongorestore
      run: sudo apt-get install -y mongodb-clients

    - name: Restaurar backup no MongoDB
      run: |
        LATEST_DIR=$(ls -td backend/backup/dump-* | head -n 1)
        mongorestore --drop --uri="${{ secrets.MONGO_URI }}" "$LATEST_DIR"
